I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 342, in script call
    call chapter1_intro
  File "game/script.rpy", line 368, in script call
    call chapter1_main
  File "game/script.rpy", line 399, in script
    jump chapter1_menu
ScriptError: could not find label 'chapter1_menu'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 342, in script call
    call chapter1_intro
  File "game/script.rpy", line 368, in script call
    call chapter1_main
  File "game/script.rpy", line 399, in script
    jump chapter1_menu
  File "/home/irman/Documents/renpy-8.3.2-sdk/renpy/ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/irman/Documents/renpy-8.3.2-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chapter1_menu'.

Linux-6.8.0-47-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.3.2.24090902
kwn_v1 1.0
Sat Oct 26 08:25:10 2024
